name = "Create Pack"
author = "MarioAndWeegee3"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c59986e2e0222fb42a54fefd6767f149375e77b5c59bd103420449f492702038"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
