name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5669cec98a16ed7f47bc21dcc0d57236b86d5c19f785656fb6a37d6b9ca19a52"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
