name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d34bd2fb3e7c76af3f68687c7dbcba189c78f696a39164b9ce3b3c014b45df6"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.75"
