name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b068652443e663fc0afb536c800d90390a40d12533ccbf4b47d485dc995edb1"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
