name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "864de352b8567ca79d657a3adda102a475f2526cef31266346460c498a73e0eb"

[versions]
minecraft = "1.19.2"
quilt = "0.18.6"
