name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.11.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f73593511336b5fc90ec75b2ba608b5c10dfaa245f568e00033dd6a8c9ee1a3"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
