name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c6e9e67dd31b49eb7ca85bce17e814429de3457ed110d6f8d5f12eec6e75e48"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
