name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.12.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6bf5b1b87976b81a4b05d65c7ca5fb145c37a02ceb1a7c49f5dbf5b7cf8c6e0"

[versions]
minecraft = "1.19.2"
quilt = "0.18.6"
