name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.23.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f5a0ce49212d0e374618fddfc40fdbc69194297b59d58a6fc6567cbba8ef36f"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"
