name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b28aa494ed537bfbc6017549f3b9a7569d52b149c7642a695a6c16f4d7001cc"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
