name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.17.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10b02144bccb4f69d4f10359696603668895270af34e574fd5021a52c855f415"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
