name = "Create Pack"
author = "MarioAndWeegee3"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "362c4aed01de648281b9d2082768993e206b05c90f6b8551f5c468b422a43422"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
