name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.18.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d88a9f7f7bb27fc92bd407a68b1665b6a5e05d85139e59e4a820f10f69b414d0"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
