name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.11.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eed16ecaad9b606e7caf6deeade6f020a9e31b31c3f2f10656ede842f57769bb"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
