name = "Create Pack"
author = "MarioAndWeegee3"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95ed7b3f63d46c9be22d1128cc184d5e96f0172ae9adbefec3367ac94103a127"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
