name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fd547f572d66ce6a7d3c8e2d9c950af9b7a505fc71008beac5c0b3d906ccbec"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
