name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.11.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d921b5ae7c5cef106d851634d8ab7d920218ed4c3f6a00eb76331df30c6a4185"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
