name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.11.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcb95b2430ba4d26580b84659a8cb790789bbfd61d1ed005680fc925854dcb7f"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
