name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff4c5ab23f3cf20496291105b2c2e6139d9b5590b3b84db7afa77fbf3a30ef84"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.29"
