name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.11.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "282db66f697f4b0a1b2182b0c9fd552119e7f6326f2e001f739f974ade89fff7"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
