name = "Create Pack"
author = "MarioAndWeegee3"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd70250d43e7595ce4ec5fd75c244414d6a9ed746a2886f1a544161dfe181c25"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
