name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.23.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a86aa00a57b88f3adb45adf00e6dcb4f99574a7b5931e33cc7f79ed425934381"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"
