name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.14.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c4c39905bfbd242f915e0246a4c8b6941aa059febdf13be046360eb619f592c"

[versions]
minecraft = "1.19.2"
quilt = "0.18.6"
