name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82f97dad081819abdf05c8fbf41872c233ce823e98484f70ea5f7d000775b565"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
