name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.11.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccbb264772c9393f73c3b5d7588b485d088f75d8fb8b55239310179d75608ae0"

[versions]
minecraft = "1.19.2"
quilt = "0.18.4-pre.3"
