name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa275031c1e6ec7c479fb93b8d6cd09c47c2fa0422ee62ba7912de926ee5007b"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.29"
