name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d21738f16913741dd1256bc1e593db4971c0d8390dbd64f74402ba0f0bcdd94"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
