name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0304ba410e3c5afbaf268ad856966a938e0766d668f4613835051bb99ece578a"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.29"
