name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.21.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05a449a077522968e4e953bc35af4664a1cc6af3f332df527a53146d8aa5b1b4"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"
