name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85795aa1625cf577146ccab68ba6cae9b3b1de1dc4794999a108e923517e650c"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.29"
