name = "Create Pack"
author = "MarioAndWeegee3"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25bdabc9870ff9bcce9bf19715e12b79c68a0ed964d0728ce314e211970e311a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
