name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.16.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a521f9961be9e217cb7d5a435f074f306728266dc232bed856ae5b8e9035cccd"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
