name = "Create Pack"
author = "MarioAndWeegee3"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "815a14e113c3b8234654b852c5933ced3f9acb6289cee4054e9914097547e5a8"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
