name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dc838738d3b296798e71b1ccf18878b1ba98d50fd2ecc255f5fc1338e988bd0"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
