name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.20.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc84b721c8318eff51e916317047713f921a578615711678d4135edc936c4fb3"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
