name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.23.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1a486832b176366294e6bd2f9d31f59b14686fc80a1e0bbd6a9ac4f5c1da0d1"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"
