name = "Create Pack"
author = "MarioAndWeegee3"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f57eaca71c7368d7245bb8e6dcfd4a76b685e35a47b48a1f9a32bbcd0cfbe69"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
