name = "Create Pack"
author = "MarioAndWeegee3"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bf7b66f69ecb8e8d4a1b4aa24ecfd93bb0bb9187d3ca537b736131823d4c3a7"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
